console.log('inserting audio tags..');
 document.getElementById('sfx-container').innerHTML = `<audio src="sfx/7_endnu.ogg" id="7_endnu" preload="auto"></audio>
<audio src="sfx/alright_lets_call_it_a_day.ogg" id="alright_lets_call_it_a_day" preload="auto"></audio>
<audio src="sfx/coin.ogg" id="coin" preload="auto"></audio>
<audio src="sfx/complaining_is_always_good.ogg" id="complaining_is_always_good" preload="auto"></audio>
<audio src="sfx/der_er_en_del_nye_oevelser.ogg" id="der_er_en_del_nye_oevelser" preload="auto"></audio>
<audio src="sfx/det_jo_ren_afslapning.ogg" id="det_jo_ren_afslapning" preload="auto"></audio>
<audio src="sfx/det_kan_jeg_godt_li.ogg" id="det_kan_jeg_godt_li" preload="auto"></audio>
<audio src="sfx/det_var_2_runder.ogg" id="det_var_2_runder" preload="auto"></audio>
<audio src="sfx/dette_er_den_nye_planke.ogg" id="dette_er_den_nye_planke" preload="auto"></audio>
<audio src="sfx/done_for_today.ogg" id="done_for_today" preload="auto"></audio>
<audio src="sfx/du_har_30_sek_tilbage.ogg" id="du_har_30_sek_tilbage" preload="auto"></audio>
<audio src="sfx/du_kommer_lige_til_din_yndlings.ogg" id="du_kommer_lige_til_din_yndlings" preload="auto"></audio>
<audio src="sfx/duuut.ogg" id="duuut" preload="auto"></audio>
<audio src="sfx/fanfare.ogg" id="fanfare" preload="auto"></audio>
<audio src="sfx/fedt.ogg" id="fedt" preload="auto"></audio>
<audio src="sfx/good_job.ogg" id="good_job" preload="auto"></audio>
<audio src="sfx/good_job2.ogg" id="good_job2" preload="auto"></audio>
<audio src="sfx/hold_boette.ogg" id="hold_boette" preload="auto"></audio>
<audio src="sfx/husk_hoften_den_sku_vaere_plan.ogg" id="husk_hoften_den_sku_vaere_plan" preload="auto"></audio>
<audio src="sfx/husk_numserne_de_skal_ned.ogg" id="husk_numserne_de_skal_ned" preload="auto"></audio>
<audio src="sfx/husk_numserne_skal_ned.ogg" id="husk_numserne_skal_ned" preload="auto"></audio>
<audio src="sfx/husk_og_hold_hoften_lee.ogg" id="husk_og_hold_hoften_lee" preload="auto"></audio>
<audio src="sfx/hvorfor_goer_vi_det_her.ogg" id="hvorfor_goer_vi_det_her" preload="auto"></audio>
<audio src="sfx/if_its_too_easy_and_doesnt_burn.ogg" id="if_its_too_easy_and_doesnt_burn" preload="auto"></audio>
<audio src="sfx/jeg_kan_godt_maerke_det_3_gang.ogg" id="jeg_kan_godt_maerke_det_3_gang" preload="auto"></audio>
<audio src="sfx/jeg_kan_ikke_goere_det.ogg" id="jeg_kan_ikke_goere_det" preload="auto"></audio>
<audio src="sfx/jeg_syns_vi_skal_springe_den_over.ogg" id="jeg_syns_vi_skal_springe_den_over" preload="auto"></audio>
<audio src="sfx/julian_lydoptager_du_det_her.ogg" id="julian_lydoptager_du_det_her" preload="auto"></audio>
<audio src="sfx/klar_til_runde_2.ogg" id="klar_til_runde_2" preload="auto"></audio>
<audio src="sfx/lee_kom_nu.ogg" id="lee_kom_nu" preload="auto"></audio>
<audio src="sfx/ned_med_numsen.ogg" id="ned_med_numsen" preload="auto"></audio>
<audio src="sfx/ned_med_numserne.ogg" id="ned_med_numserne" preload="auto"></audio>
<audio src="sfx/nice_slow.ogg" id="nice_slow" preload="auto"></audio>
<audio src="sfx/nu_gider_jeg_ikke_lave_den_mere.ogg" id="nu_gider_jeg_ikke_lave_den_mere" preload="auto"></audio>
<audio src="sfx/ready.ogg" id="ready" preload="auto"></audio>
<audio src="sfx/skub_biseps_fremad.ogg" id="skub_biseps_fremad" preload="auto"></audio>
<audio src="sfx/skulder_klap.ogg" id="skulder_klap" preload="auto"></audio>
<audio src="sfx/stille_og_rolige_bevaegelser.ogg" id="stille_og_rolige_bevaegelser" preload="auto"></audio>
<audio src="sfx/that_was_the_first_set.ogg" id="that_was_the_first_set" preload="auto"></audio>
<audio src="sfx/tuk_tuk3.ogg" id="tuk_tuk3" preload="auto"></audio>
<audio src="sfx/tuk_tuk_en_gang.ogg" id="tuk_tuk_en_gang" preload="auto"></audio>
<audio src="sfx/tuktuk.ogg" id="tuktuk" preload="auto"></audio>
<audio src="sfx/tuktuk2.ogg" id="tuktuk2" preload="auto"></audio>
<audio src="sfx/tuktuk4.ogg" id="tuktuk4" preload="auto"></audio>
<audio src="sfx/uden_at_boeje_albuerne.ogg" id="uden_at_boeje_albuerne" preload="auto"></audio>
<audio src="sfx/up_with_your_butts.ogg" id="up_with_your_butts" preload="auto"></audio>
<audio src="sfx/vi_goer_klar_til_diagonal.ogg" id="vi_goer_klar_til_diagonal" preload="auto"></audio>
<audio src="sfx/vi_kan_godt_grine_igennem_det_naeste.ogg" id="vi_kan_godt_grine_igennem_det_naeste" preload="auto"></audio>
<audio src="sfx/vi_venter_lige_paa_oliver.ogg" id="vi_venter_lige_paa_oliver" preload="auto"></audio>
<audio src="sfx/whoow.ogg" id="whoow" preload="auto"></audio>` 

